### ISSUE TITLE
Fix header image appearing between logo and menu.

### ISSUE THREAD

**Issue by chriswallace** [godaddy/wp-lyrical-theme#1]
Same as the issue on the Ascension theme.

**Comment by imbradmiller** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;7TjZSrg1&#x2F;21-lyrical-photography-theme"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Lyrical (Photography Theme)</a>
