### ISSUE TITLE
Background color bleed on submenu items in mobile nav

### ISSUE THREAD

**Issue by frankiejarrett** [godaddy/wp-lyrical-theme#17]
<img width="330" alt="screen_shot_2016-08-26_at_2_28_09_pm" src="https://cloud.githubusercontent.com/assets/522158/18017914/8660208e-6b99-11e6-8c67-0451390c0b6a.png">

**Comment by mrpritchett** [comment]
No longer bleeding through. There is a small issue of certain items' borders not showing. Closing this issue in favor of tracking the remaining issue in https://github.com/godaddy/wp-lyrical-theme/issues/18
