### ISSUE TITLE
Horizontal border thickness not consistent across menu items on mobile

### ISSUE THREAD

**Issue by frankiejarrett** [godaddy/wp-lyrical-theme#18]
Perhaps this was intentional? Not sure. Possibly related to #17.

<img width="348" alt="screen shot 2016-08-26 at 2 30 14 pm" src="https://cloud.githubusercontent.com/assets/522158/18017938/a8a43bda-6b99-11e6-85fa-062d5b861bdb.png">

**Comment by mrpritchett** [comment]
Fixed.
