### ISSUE TITLE
Adjust the header to match design

### ISSUE THREAD

**Issue by chriswallace** [godaddy/wp-lyrical-theme#2]
Please adjust the header to closer align with the design of the mockup.

http://lift.d.pr/1jZQp

Color of the text should be white, menu items need to be smaller and tagline should be a bit smaller.

**Comment by imbradmiller** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;7TjZSrg1&#x2F;21-lyrical-photography-theme"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Lyrical (Photography Theme)</a>

**Comment by tobeycodes** [comment]
Chris, some of these were just because you changed the font and colors in customizer. I've made some small amends though
