### ISSUE TITLE
Changing header text

### ISSUE THREAD

**Issue by assyla** [godaddy/wp-lyrical-theme#24]
Hello,
I'm quite the noob at this but I'm making a website for myself using this theme but I can't get the header text to change. It says "Make a bold statement
Grab your visitors' attention front and center on your homepage, then give them an action to take." 

I've tried other themes and they have a space to edit the header in the "Customize" section but not Lyrical. I'm loving the look but I need to change the header. 

Much appreciated!

**Comment by jonathanbardo** [comment]
Hey @assyla,

Thanks for reporting this! You should be able to modify this text in the text widget of the hero sidebar (http://YOURDOMAIN.COM/wp-admin/widgets.php). 
<img width="1093" alt="screen_shot_2016-09-14_at_7_12_01_pm" src="https://cloud.githubusercontent.com/assets/1933681/18533191/329cba14-7aaf-11e6-8630-c508c37e8c19.png">

We are working on making this a little more obvious for users as we understand it's a little hidden at the moment. 

Have a great day!

**Comment by assyla** [comment]
Amazing! Thank you :)
