### ISSUE TITLE
Make RSS text part of the custom footer colors (same color as links)

### ISSUE THREAD

**Issue by chriswallace** [godaddy/wp-lyrical-theme#3]
http://lift.d.pr/12Ugj

**Comment by imbradmiller** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;7TjZSrg1&#x2F;21-lyrical-photography-theme"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Lyrical (Photography Theme)</a>

**Comment by tobeycodes** [comment]
Fixed as part of next commit
