### ISSUE TITLE
Changing Transparency of Header Image

### ISSUE THREAD

**Issue by westco** [godaddy/wp-lyrical-theme#35]
I have been looking through the CSS and I can't seem to find where I can adjust the Transparency of the header image. I am wanting to lighten it up a bit more. Thank you

**Comment by jonathanbardo** [comment]
Hey @westco,

No need to change the CSS. Everything happens in the customizer. (Don't mind the reference to Primer in the following screenshots)
![screen_shot_2016-10-14_at_3_05_19_pm](https://cloud.githubusercontent.com/assets/1933681/19399506/d1ff0a3a-921f-11e6-98b1-504e94cc163c.png)
![screen_shot_2016-10-14_at_3_05_28_pm](https://cloud.githubusercontent.com/assets/1933681/19399505/d1f63b08-921f-11e6-92bf-fcae0ef970c4.png)
![screen_shot_2016-10-14_at_3_05_33_pm](https://cloud.githubusercontent.com/assets/1933681/19399504/d1f29cfa-921f-11e6-84bf-23727ecfa307.png)
