### ISSUE TITLE
Add option to change menu background color drop-downs/hover in Customize menu

### ISSUE THREAD

**Issue by MrJackSprat** [godaddy/wp-lyrical-theme#37]

**Comment by EvanHerman** [comment]
Hi @MrJackSprat ,

Thanks for suggesting this new feature. We can certainly see the benefits to adding an additional option to alter the background color, and will look into doing so in an upcoming release. The background color should be inheriting the color from the selected color scheme, with the option to override - similar to how the button background colors work.

In regards to the hover color, this should be a semi transparent color inherited from the menu background color, so this won't be added as an option but will be controlled by the color selected for the background of the menu itself.

Evan
