### ISSUE TITLE
Blog Author page shows span code

### ISSUE THREAD

**Issue by linuxgemini** [godaddy/wp-lyrical-theme#51]
*I haven't tested this on other themes though.*

Using Wordpress 4.9.1 with the latest version of Primer and Lyrical.

![2017-12-13_00-04-04](https://user-images.githubusercontent.com/4682655/33908344-2a149448-df99-11e7-87ea-a336b1f9a51d.png)

**Comment by EvanHerman** [comment]
Hi @linuxgemini ,

We have a new release we are working on getting out the door that should resolve this issue. Sit tight, I'll post back here when we have it shipped.

**Comment by EvanHerman** [comment]
We've release **Primer 1.8.1** and **Lyrical 1.1.1**:
https://github.com/godaddy/wp-primer-theme/releases/tag/v1.8.1
https://github.com/godaddy/wp-lyrical-theme/releases/tag/v1.1.1

Update both themes and the issue you are facing should be resolved. Feel free to let us know if it's not.
