### ISSUE TITLE
Unwanted background in the main menu after the upgrade to v1.1.1

### ISSUE THREAD

**Issue by altumlabs** [godaddy/wp-lyrical-theme#55]
I upgraded to the latest version of the theme a week ago and noticed that the main menu has a background color when viewing on the large screen. It used to be transparent. I saw in the release notes that there was some kind of fix to the background of the pop up menu. Assuming that change broke this. 

You can see it on the altumlabs.com site. I tried Chrome and Safari. I do not have any custom CSS. Everything out-of-the-box.

**Comment by EvanHerman** [comment]
Sorry for the delay in responding here. It looks like you may have resolved the issue on your end. If for some reason you did not and I just overlooked it, feel free to post back here and I'll be glad to help out any way I can.

**Comment by FineonX** [comment]
Hello, Can you please post how to get this issue fixed, I need the menu back transparent and can't find the way to fix it.
