### ISSUE TITLE
Footer Widget Text Color

### ISSUE THREAD

**Issue by RollaRoaster** [godaddy/wp-lyrical-theme#56]
If you look at www.whitepinemotel.com.... you can see that the text in the footers is mostly black on the dark blue background... I cannot find a way to change the text to white.. I need both the titles... and the text in the footer widget area's to be white.... Help Please.

**Comment by EvanHerman** [comment]
Hi @RollaRoaster 

You should be able to adjust the color of the widget titles and text inside the contact widget with the following CSS:

```css
.site-footer .widget-title,
.site-footer .widget {
   color: white;
}
```

You can add that to the Additional CSS section in the customizer. You can get there from the dashboard by going to 'Appearance > Customize > Additional CSS'.

Let us know if that helps!

**Comment by RollaRoaster** [comment]
Hello!
How do I add that to the footer widget?  As a HTML code?  I tried that...
and it didn't work...  I also tried adding to the customize
additional CSS.. didn't work either...???

*Stephanie Deyo*
WebInk Designing & Printing
webinkdesigning@gmail.com
Check out my website!!! www.WebinkDesigning.com
Location: 699 Michigan, Orofino Idaho
Mailing Address: 2237 Dent Bridge Road
O: 208-476-9060

Modern & Inventive Website, Graphic & Print Design & Printing Solutions

*PRINTING NOTICE:*
Please proofread everything before giving me the "final go ahead" for
printing.  Please be aware that once you approve your final proof for
printing no changes can be made... if there is an error (made by either
myself or you) you will still be responsible for paying full price for the
product.  Thank you!

**Comment by EvanHerman** [comment]
It should go into the additional CSS section of the customizer, exactly how I've written it above. That's the best and easiest location to place it. I've tested it locally on my end, and it does appear to be working properly.

Feel free to also try and alter the 'Color' setting in the customizer to achieve your desired result.

**Comment by RollaRoaster** [comment]
The "Widget" Color setting in the Customizer did work.  Thank you!

*Stephanie Deyo*
WebInk Designing & Printing
webinkdesigning@gmail.com
Check out my website!!! www.WebinkDesigning.com
Location: 699 Michigan, Orofino Idaho
Mailing Address: 2237 Dent Bridge Road
O: 208-476-9060

Modern & Inventive Website, Graphic & Print Design & Printing Solutions

*PRINTING NOTICE:*
Please proofread everything before giving me the "final go ahead" for
printing.  Please be aware that once you approve your final proof for
printing no changes can be made... if there is an error (made by either
myself or you) you will still be responsible for paying full price for the
product.  Thank you!

**Comment by EvanHerman** [comment]
Great - thank you for keeping us in the loop. Have a great rest of your day!
