### ISSUE TITLE
Menu can't be transparent after upgrading to latest version

### ISSUE THREAD

**Issue by FineonX** [godaddy/wp-lyrical-theme#61]
I upgraded to the latest version of the theme and noticed that the main menu has a background color when viewing on the PC screen. It used to be transparent. how can we fix that?

**Comment by EvanHerman** [comment]
Hi @FineonX ,

It does appear that way, as it looks like saving an empty value in the menu color field does not produce a transparent color for the menu.

What you can do, is add the following small snippet of CSS to the 'Additional CSS' section of the customizer to get that menu transparent.

```css
.main-navigation {
   background-color: transparent !important;
}
```

But keep in mind that this is going to make the navigation transparent on mobile devices, which might not look great depending on your hero image and the length of the mobile menu (if it overlaps with the white content background beneath).

Evan

**Comment by FineonX** [comment]
Thank you... for fixing the mobile screens, I am adding these:

.main-navigation {
   background-color: transparent !important;
}
  @media only screen and (max-width: 61.063em) {
.main-navigation {
   background-color: black !important;
} }

looks like it worked

**Comment by EvanHerman** [comment]
Great!
