### ISSUE TITLE
Video embed blocks are in the wrong position

### ISSUE THREAD

**Issue by carolinan** [godaddy/wp-lyrical-theme#65]
When I add a full width video block, the alignment is incorrect.
The problem is:

1) The video is not*in full width even when the full width option has been selected.
2) The video is aligned all the way to the left of the website, and not
contained inside the actual post area.

To reproduce this, test the theme with the Theme Unit Test.
https://github.com/WPTRT/theme-unit-test
And view the post: Block category: Embeds.

This problem is not present in the parent theme.

![vidoeblock](https://user-images.githubusercontent.com/7422055/63481792-ff5e0100-c496-11e9-9789-1e3f4b19b89c.png)

**Comment by AnthonyLedesma** [comment]
I am closing issues in preparation for archiving the repo.
