### ISSUE TITLE
Skip to content link has a color contrast that is too low

### ISSUE THREAD

**Issue by carolinan** [godaddy/wp-lyrical-theme#66]
The skip to content link that is visible on focus uses the background color 0000ff
and the text color 4c99ba. 
These two colors only have a contrast ratio of  2.69:1 which means that many visitors will have a difficult time to read the text.

This defeats the whole purpose of the skip link (-Which is also required buy the WordPress.org Theme Review Team).

Not to mention, the background color does not match the theme at all. The sharp dark blue really stands out (Read: it looks really ugly).

**Comment by richtabor** [comment]
Thanks for the report @carolinan - really appreciated! We'll get on this. 👍

**Comment by AnthonyLedesma** [comment]
I am closing issues in preparation for archiving the repo.
