### ISSUE TITLE
Multi level menu on fluid layout go out of screen

### ISSUE THREAD

**Issue by jonathanbardo** [godaddy/wp-lyrical-theme#9]
When having a multi level menu on fluid layout, the menu goes out of frame. 
![screen shot 2016-08-12 at 3 08 13 pm](https://cloud.githubusercontent.com/assets/1933681/17634064/b58f0812-609e-11e6-9788-eb83a3f66a33.png)

Tested on Firefox and Chrome latest.

**Comment by frankiejarrett** [comment]
@jbardo This actually needs to be fixed in Primer

**Comment by jonathanbardo** [comment]
Oh oups closing...
